# Generated by Django 3.2.16 on 2025-12-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_auto_20251207_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='author',
        ),
    ]
